### ISSUE TITLE
npm start issue

### ISSUE THREAD

**Issue by Swdika** [Swdika/melement#7]
After I installed everything correctly ,npm start won't work

`npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gui@1.0.0 start: electron .
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gui@1.0.0 start script.
` 

Full Log:

`9 verbose lifecycle gui@1.0.0~start: CWD:*****/melement/gui
10 silly lifecycle gui@1.0.0~start: Args: [ '-c', 'electron .' ]
11 silly lifecycle gui@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle gui@1.0.0~start: Failed to exec start script
13 verbose stack Error: gui@1.0.0 start: "electron ."
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid gui@1.0.0
15 verbose cwd /*****/melement/gui
16 verbose *****(linux kernel name)
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v12.18.4
19 verbose npm  v6.14.8
20 error code ELIFECYCLE
21 error errno 1
22 error gui@1.0.0 start: `electron .`
22 error Exit status 1
23 error Failed at the gui@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
`

**Comment by Swdika** [comment]
Resolved...Make sure the chrome-sandbox is owned by root and has mode 4755.

`$ sudo chown root /gui/node_modules/electron/dist/chrome-sandbox
`
`$ sudo chmod 4755 /gui/node_modules/electron/dist/chrome-sandbox`
